import { Incident, Repository, ScanRun, TelemetryData } from "./api";

export const SAMPLE_REPOSITORIES: Repository[] = [
  {
    id: "repo-sample-01",
    organization_id: "org-sample",
    full_name: "acme-corp/api-gateway",
    clone_url: "https://github.com/acme-corp/api-gateway.git",
    default_branch: "main",
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "repo-sample-02",
    organization_id: "org-sample",
    full_name: "acme-corp/payment-service",
    clone_url: "https://github.com/acme-corp/payment-service.git",
    default_branch: "main",
    is_active: true,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "repo-sample-03",
    organization_id: "org-sample",
    full_name: "acme-corp/frontend-portal",
    clone_url: "https://github.com/acme-corp/frontend-portal.git",
    default_branch: "production",
    is_active: true,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SAMPLE_INCIDENTS: Incident[] = [
  {
    id: "inc-sample-01",
    repository_id: "repo-sample-01",
    rule_id: "github-pat",
    rule_name: "GitHub Personal Access Token",
    severity: "CRITICAL",
    status: "OPEN",
    verification_status: "ACTIVE",
    verification_details: "Active token verified via GitHub API /user endpoint with repo and workflow permissions.",
    file_path: ".github/workflows/deploy.yml",
    line_number: 42,
    masked_snippet: "ghp_k91b****************************",
    commit_sha: "a3f8901b2c45d67e890123456789abcdef012345",
    committer_handle: "dev-lead",
    fingerprint: "fp-github-pat-deploy-yml-42",
    first_seen_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    last_seen_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: "inc-sample-02",
    repository_id: "repo-sample-02",
    rule_id: "aws-secret-key",
    rule_name: "AWS Secret Access Key",
    severity: "CRITICAL",
    status: "OPEN",
    verification_status: "ACTIVE",
    verification_details: "Active AWS credentials confirmed via AWS STS GetCallerIdentity probe.",
    file_path: "config/aws_credentials.json",
    line_number: 14,
    masked_snippet: "wJal************************************",
    commit_sha: "98c21ea7654b3210fedcba9876543210abcdef12",
    committer_handle: "cloud-admin",
    fingerprint: "fp-aws-secret-key-14",
    first_seen_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    last_seen_at: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: "inc-sample-03",
    repository_id: "repo-sample-01",
    rule_id: "slack-webhook",
    rule_name: "Slack Incoming Webhook URL",
    severity: "HIGH",
    status: "OPEN",
    verification_status: "UNVERIFIABLE",
    verification_details: "Webhook URL pattern matched; probe skipped due to security sandbox policy.",
    file_path: "src/notifications/slack.ts",
    line_number: 28,
    masked_snippet: "https://hooks.slack.com/services/T00/B00/*********",
    commit_sha: "51fa8b29c48e7102938475610293847561029384",
    committer_handle: "bot-dev",
    fingerprint: "fp-slack-webhook-28",
    first_seen_at: new Date(Date.now() - 86400000).toISOString(),
    last_seen_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "inc-sample-04",
    repository_id: "repo-sample-03",
    rule_id: "stripe-secret-key",
    rule_name: "Stripe Live Secret Key",
    severity: "CRITICAL",
    status: "RESOLVED",
    verification_status: "REVOKED",
    verification_details: "Key revoked in Stripe Dashboard. Inactive key response 401 Unauthorized.",
    file_path: "apps/checkout/stripe_client.py",
    line_number: 88,
    masked_snippet: "sk_live_51H*************************",
    commit_sha: "33bc91aa8761234567890abcdef1234567890abc",
    committer_handle: "backend-eng",
    fingerprint: "fp-stripe-secret-key-88",
    first_seen_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    last_seen_at: new Date(Date.now() - 86400000).toISOString(),
    resolved_at: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const SAMPLE_SCANS: ScanRun[] = [
  {
    id: "scan-sample-01",
    repository_id: "repo-sample-01",
    commit_sha: "a3f8901b2c45d67e890123456789abcdef012345",
    branch: "main",
    trigger_source: "push",
    status: "COMPLETED",
    files_scanned: 184,
    total_findings: 1,
    active_leaks_count: 1,
    duration_ms: 38,
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: "scan-sample-02",
    repository_id: "repo-sample-02",
    commit_sha: "98c21ea7654b3210fedcba9876543210abcdef12",
    branch: "main",
    trigger_source: "push",
    status: "COMPLETED",
    files_scanned: 92,
    total_findings: 1,
    active_leaks_count: 1,
    duration_ms: 29,
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: "scan-sample-03",
    repository_id: "repo-sample-03",
    commit_sha: "77aa11223344556677889900aabbccddeeff0011",
    branch: "production",
    trigger_source: "push",
    status: "COMPLETED",
    files_scanned: 312,
    total_findings: 0,
    active_leaks_count: 0,
    duration_ms: 54,
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const SAMPLE_TELEMETRY: TelemetryData = {
  total_repositories: 3,
  total_scans: 12,
  total_incidents: 4,
  active_leaks: 2,
  resolved_incidents: 1,
  critical_count: 3,
  high_count: 1,
  medium_count: 0,
  low_count: 0,
  mean_time_to_remediate_hours: 1.4,
  recent_incidents: SAMPLE_INCIDENTS,
  recent_scans: SAMPLE_SCANS,
};
