"""create_initial_schema

Revision ID: e0660924cbac
Revises: 
Create Date: 2026-09-05 21:04:44.219432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0660924cbac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('clone_url', sa.String(length=512), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('webhook_secret', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_full_name'), 'repositories', ['full_name'], unique=False)
    op.create_index(op.f('ix_repositories_github_repo_id'), 'repositories', ['github_repo_id'], unique=False)
    op.create_index(op.f('ix_repositories_organization_id'), 'repositories', ['organization_id'], unique=False)
    op.create_table('scan_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('trigger_source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('files_scanned', sa.Integer(), nullable=False),
    sa.Column('total_findings', sa.Integer(), nullable=False),
    sa.Column('active_leaks_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_runs_commit_sha'), 'scan_runs', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_scan_runs_repository_id'), 'scan_runs', ['repository_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('scan_run_id', sa.UUID(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('encrypted_secret_blob', sa.LargeBinary(), nullable=True),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verification_details', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('masked_snippet', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('committer_handle', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'fingerprint', name='uq_repo_fingerprint')
    )
    op.create_index(op.f('ix_incidents_fingerprint'), 'incidents', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_incidents_repository_id'), 'incidents', ['repository_id'], unique=False)
    op.create_index(op.f('ix_incidents_rule_id'), 'incidents', ['rule_id'], unique=False)
    op.create_index(op.f('ix_incidents_scan_run_id'), 'incidents', ['scan_run_id'], unique=False)
    op.create_index(op.f('ix_incidents_secret_hash'), 'incidents', ['secret_hash'], unique=False)
    op.create_table('incident_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('previous_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_audits_incident_id'), 'incident_audits', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_audits_incident_id'), table_name='incident_audits')
    op.drop_table('incident_audits')
    op.drop_index(op.f('ix_incidents_secret_hash'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_scan_run_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_rule_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_repository_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_fingerprint'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_scan_runs_repository_id'), table_name='scan_runs')
    op.drop_index(op.f('ix_scan_runs_commit_sha'), table_name='scan_runs')
    op.drop_table('scan_runs')
    op.drop_index(op.f('ix_repositories_organization_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_github_repo_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_full_name'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
