import logging
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.crypto import (
    compute_blind_index,
    compute_incident_fingerprint,
    encrypt_secret,
)
from app.core.database import get_db
from app.core.security import get_current_user
from app.models.audit import IncidentAudit
from app.models.incident import Incident
from app.models.organization import Organization
from app.models.repository import Repository
from app.models.scan_run import ScanRun
from app.models.user import User
from app.schemas.scan_run import CliScanPayload, CliScanResponse
from app.services.notifications import (
    send_discord_scan_summary_alert,
    send_slack_scan_summary_alert,
)

logger = logging.getLogger("aegis.scans.cli")
router = APIRouter()


@router.post(
    "/cli",
    response_model=CliScanResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Ingest scan results streamed from Aegis CLI (aegis scan --sync)",
)
async def ingest_cli_scan(
    payload: CliScanPayload,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Ingests local workstation scan reports generated by 'aegis scan --sync'.
    Records the ScanRun under trigger_source='cli', tracks or creates incidents
    with deterministic blind-indexing, and alerts configured workspace webhooks.
    """
    if not current_user.organization_id:
        default_org_stmt = select(Organization).where(Organization.slug == "default-org")
        org = (await db.execute(default_org_stmt)).scalar_one_or_none()
        if not org:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="User does not have an active organization workspace.",
            )
        target_org_id = org.id
    else:
        target_org_id = current_user.organization_id

    # 1. Resolve or auto-register local repository in workspace
    repo_name = (payload.repository_name or "local-workstation").strip().lstrip("/")
    stmt = select(Repository).where(
        Repository.full_name == repo_name,
        Repository.organization_id == target_org_id,
    )
    repo = (await db.execute(stmt)).scalar_one_or_none()

    if not repo:
        import secrets
        clone_url = payload.clone_url or f"https://github.com/{repo_name}.git"
        repo = Repository(
            organization_id=target_org_id,
            full_name=repo_name,
            clone_url=clone_url,
            default_branch=payload.branch or "main",
            webhook_secret=secrets.token_hex(20),
            is_active=True,
        )
        db.add(repo)
        await db.commit()
        await db.refresh(repo)

    now = datetime.now(timezone.utc)

    # 2. Create ScanRun record with trigger_source='cli'
    scan_run = ScanRun(
        repository_id=repo.id,
        commit_sha=(payload.commit_sha or "LOCAL_HEAD")[:64],
        branch=(payload.branch or "local")[:255],
        trigger_source="cli",
        status="COMPLETED",
        files_scanned=payload.total_files_scanned,
        total_findings=payload.total_findings,
        active_leaks_count=payload.active_leaks_count,
        duration_ms=payload.duration_ms,
        started_at=now,
        completed_at=now,
    )
    db.add(scan_run)
    await db.commit()
    await db.refresh(scan_run)

    # 3. Process Findings & Deduplicate Incidents
    incidents_recorded = 0
    regressions_count = 0
    alert_findings: List[Dict[str, Any]] = []

    for f in payload.findings:
        verif = f.verification or {}
        verif_status = verif.get("status", "NOT_VERIFIED")
        verif_details = verif.get("details", "")
        masked_val = f.masked_value or "****"
        severity = (f.severity or "HIGH").upper()
        if severity not in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
            severity = "HIGH"

        token_identity = f"{masked_val}:{f.id}" if f.id else masked_val
        secret_hash = compute_blind_index(token_identity)
        fingerprint = compute_incident_fingerprint(
            str(repo.id), f.rule_id, f.file_path, secret_hash
        )

        # Check existing incident
        inc_stmt = select(Incident).where(
            Incident.repository_id == repo.id,
            Incident.fingerprint == fingerprint,
        )
        existing = (await db.execute(inc_stmt)).scalar_one_or_none()

        if existing:
            prev_status = existing.status
            existing.last_seen_at = now
            existing.verification_status = verif_status
            existing.verification_details = verif_details
            existing.commit_sha = scan_run.commit_sha
            existing.committer_handle = current_user.email
            existing.scan_run_id = scan_run.id

            if prev_status in ("RESOLVED", "DISMISSED"):
                regressions_count += 1
                existing.status = "REGRESSION"
                existing.severity = "CRITICAL"
                existing.resolved_at = None
                audit = IncidentAudit(
                    incident_id=existing.id,
                    actor_id=current_user.email,
                    action="REGRESSION_DETECTED",
                    previous_state={"status": prev_status},
                    new_state={"status": "REGRESSION", "trigger": "cli_sync"},
                )
                db.add(audit)
        else:
            inc = Incident(
                repository_id=repo.id,
                scan_run_id=scan_run.id,
                rule_id=f.rule_id,
                rule_name=f.title or f.rule_id,
                severity=severity,
                status="OPEN",
                verification_status=verif_status,
                verification_details=verif_details,
                file_path=f.file_path,
                line_number=f.line_number,
                masked_snippet=masked_val,
                commit_sha=scan_run.commit_sha,
                committer_handle=current_user.email,
                secret_hash=secret_hash,
                encrypted_secret_blob=encrypt_secret(masked_val),
                fingerprint=fingerprint,
                first_seen_at=now,
                last_seen_at=now,
            )
            db.add(inc)
            incidents_recorded += 1
            await db.flush()

            audit = IncidentAudit(
                incident_id=inc.id,
                actor_id=current_user.email,
                action="CLI_FINDING_RECORDED",
                new_state={"status": "OPEN", "rule": f.rule_id, "trigger": "cli_sync"},
            )
            db.add(audit)

        if severity in ("CRITICAL", "HIGH") or verif_status == "ACTIVE":
            alert_findings.append({
                "rule_id": f.rule_id,
                "rule_name": f.title or f.rule_id,
                "severity": severity,
                "file_path": f.file_path,
                "line_number": f.line_number,
                "masked_snippet": masked_val,
                "verification_status": verif_status,
            })

    await db.commit()

    # 4. Dispatch Alert Notifications if Critical/Active Findings Exist
    if alert_findings or regressions_count > 0:
        org = await db.get(Organization, target_org_id)
        slack_url = (org.slack_webhook_url if org and org.slack_webhook_url else None) or settings.SLACK_WEBHOOK_URL
        discord_url = org.discord_webhook_url if org and org.discord_webhook_url else None

        if slack_url and slack_url.strip():
            await send_slack_scan_summary_alert(
                repo_name=repo.full_name,
                branch=scan_run.branch,
                commit_sha=scan_run.commit_sha,
                committer=current_user.email,
                total_findings=len(payload.findings),
                active_leaks_count=payload.active_leaks_count,
                critical_count=payload.critical_count,
                findings=alert_findings,
                regressions_count=regressions_count,
                webhook_url=slack_url,
            )
        if discord_url and discord_url.strip():
            await send_discord_scan_summary_alert(
                webhook_url=discord_url,
                repo_name=repo.full_name,
                branch=scan_run.branch,
                commit_sha=scan_run.commit_sha,
                committer=current_user.email,
                total_findings=len(payload.findings),
                active_leaks_count=payload.active_leaks_count,
                critical_count=payload.critical_count,
                findings=alert_findings,
                regressions_count=regressions_count,
            )

    return CliScanResponse(
        scan_run_id=scan_run.id,
        repository_id=repo.id,
        repository_name=repo.full_name,
        status="synced",
        incidents_recorded=incidents_recorded,
        active_leaks=payload.active_leaks_count,
        message=f"CLI scan synced to Aegis Control Plane. {incidents_recorded} new incident(s) recorded.",
    )
